apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: places-hpa
spec:
  maxReplicas: 2 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  targetCPUUtilizationPercentage: 90 # target CPU utilization